[package]
name = "Rex"
version = "1.2.0"
edition = "2024"

[dependencies]
tar = "0.4"
zstd = "0.13"
fs_extra = "1.3"
rldd-rex = "1.0"

[profile.release]
opt-level = "z"
panic = "abort"
codegen-units = 1
lto = true
strip = true
debug = false
overflow-checks = false